### ISSUE TITLE
readme review

### ISSUE THREAD

**Issue by williamsgareth** [GarethW1994/registrations_numbers_webapp#1]
Could you review my readme file when you get a chance too. Thanks. @ggsbv

**Comment by ggsbv** [comment]
@GarethW1994 

Very nice. The screenshot of the app is a very nice touch, and your development section is very detailed and easy to follow. No qualms at all, good stuff

**Comment by williamsgareth** [comment]
@MANtor123 - Please install my registration application by following the readme provided. Thanks

**Comment by MANtor123** [comment]
@GarethW1994 

the Readme file is very nice, and well structured. It is easy to follow and detailed as well.
  
The app is running online, but it is not running locally.
Can you be more specific on telling the user how to run it locally like being more specific.

But anyway good job

**Comment by williamsgareth** [comment]
@MANtor123  okay I've fixed that issue. Can you try again please and let me know. Thanks.

**Comment by williamsgareth** [comment]
@MANtor123 within the index.js file change the Models.registrations to just Models that should fix the issue. I've updated the change on my repo thanks.

**Comment by MANtor123** [comment]
@GarethW1994 

It has worked.
